### ISSUE TITLE
Inviting all members of Sahara to GCP 

### ISSUE THREAD

**Issue by pranthicavuturu** [Food-Oasis/Sahara-Repo#20]

**Comment by rjdoubleu** [comment]
- [x] Ryan
- [x] Pranthi
- [x] Sai
- [x] Ayobami
- [x] Jingjing

**Comment by rjdoubleu** [comment]
![permissions](https://user-images.githubusercontent.com/17189478/66093634-0df00b80-e55f-11e9-80bf-a83159668b43.PNG)
