### ISSUE TITLE
Creating the tables 

### ISSUE THREAD

**Issue by pranthicavuturu** [Food-Oasis/Sahara-Repo#21]

**Comment by rjdoubleu** [comment]
initial tables have been deployed, these will be removed at our next project meeting among the various teams
![buyer table](https://user-images.githubusercontent.com/17189478/66093471-607cf800-e55e-11e9-8d71-72467d72de34.PNG)
![carts](https://user-images.githubusercontent.com/17189478/66093472-607cf800-e55e-11e9-87cc-db0c80da4f6b.PNG)
![product table](https://user-images.githubusercontent.com/17189478/66093473-607cf800-e55e-11e9-9f8d-d4505d7074b2.PNG)
![review table](https://user-images.githubusercontent.com/17189478/66093474-607cf800-e55e-11e9-9871-46e8eb28e41c.PNG)
![seller tables](https://user-images.githubusercontent.com/17189478/66093475-607cf800-e55e-11e9-8f3c-9320e85fd6ad.PNG)
![tables](https://user-images.githubusercontent.com/17189478/66093476-607cf800-e55e-11e9-8408-a7fa82d0b7f3.PNG)
